#!/usr/bin/env bash
# Baseline benchmarks for pomo.
# Measures `pomo status --json` cold-start (idle + warm) and the release binary size.
# Writes a markdown table to bench/baseline.md and stdout.
#
# Requires: bash, cargo. Optional: hyperfine (preferred) - falls back to a
# 10-iteration bash loop using `date +%s%N`.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

BIN="$ROOT/target/release/pomo"
OUT="$ROOT/bench/baseline.md"
ITERS=10

echo "==> cargo build --release"
cargo build --release --quiet

if [ ! -x "$BIN" ]; then
    echo "error: $BIN missing after build" >&2
    exit 1
fi

# Stage a warm state file by hand-writing a minimal valid State.
# pomo's TUI cannot run without a real terminal, so we cannot ask it to
# produce one for us.
STATE_DIR="$(mktemp -d)"
IDLE_DIR="$(mktemp -d)"
trap 'rm -rf "$STATE_DIR" "$IDLE_DIR"' EXIT

mkdir -p "$STATE_DIR/pomo"
UPDATED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
cat > "$STATE_DIR/pomo/state.json" <<JSON
{"label":"Work","kind":"work","remaining_secs":1234,"total_secs":1500,"paused":false,"updated_at":"$UPDATED_AT"}
JSON

bench_one() {
    # $1: label, $2: env prefix (e.g. "XDG_RUNTIME_DIR=$IDLE_DIR"), $3...: command
    local label="$1"; shift
    local env_prefix="$1"; shift
    local cmd="$*"

    if command -v hyperfine >/dev/null 2>&1; then
        # hyperfine prints a summary; grab the mean.
        local result
        result=$(env $env_prefix hyperfine --warmup 3 --runs "$ITERS" --export-markdown /dev/stdout "$cmd" 2>/dev/null \
            | awk -F'|' '/^\| `/ {print $3; exit}' \
            | sed 's/^ *//;s/ *$//')
        echo "$result"
    else
        # Fallback: 10 iterations, report mean in ms.
        local total=0
        for _ in $(seq 1 "$ITERS"); do
            local t0 t1
            t0=$(date +%s%N)
            env $env_prefix bash -c "$cmd" >/dev/null 2>&1
            t1=$(date +%s%N)
            total=$(( total + (t1 - t0) ))
        done
        # ns -> ms with one decimal
        local mean_ns=$(( total / ITERS ))
        local ms_int=$(( mean_ns / 1000000 ))
        local ms_frac=$(( (mean_ns / 100000) % 10 ))
        echo "${ms_int}.${ms_frac} ms (n=${ITERS}, bash timer)"
    fi
}

echo "==> measuring"
IDLE_TIME=$(bench_one "status-idle" "XDG_RUNTIME_DIR=$IDLE_DIR" "$BIN status --json")

WARM_TIME=$(bench_one "status-warm" "XDG_RUNTIME_DIR=$STATE_DIR" "$BIN status --json")

BIN_SIZE=$(ls -l "$BIN" | awk '{print $5}')
BIN_SIZE_HUMAN=$(numfmt --to=iec --suffix=B "$BIN_SIZE" 2>/dev/null || echo "$BIN_SIZE bytes")

COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
DATE=$(date -u +%Y-%m-%d)

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# pomo baseline

Generated by \`bench/run.sh\`. Commit: \`$COMMIT\`. Date: $DATE (UTC).

| metric                       | value                |
| ---------------------------- | -------------------- |
| \`pomo status --json\` (idle)  | $IDLE_TIME           |
| \`pomo status --json\` (warm)  | $WARM_TIME           |
| release binary size          | $BIN_SIZE_HUMAN      |

Tooling: $(command -v hyperfine >/dev/null 2>&1 && echo "hyperfine" || echo "bash + date +%s%N (fallback)")
EOF

echo
cat "$OUT"
